In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
from yahooquery import search

In [2]:
a="S&P 500"

In [3]:
search_results=search(a)
search_results

{'explains': [],
 'count': 12,
 'quotes': [{'exchange': 'NGM',
   'quoteType': 'EQUITY',
   'symbol': 'ACSP',
   'index': 'quotes',
   'score': 100001.0,
   'typeDisp': 'Equity',
   'longname': 'ProShares S&P 500 Autocallable Income ETF',
   'exchDisp': 'NASDAQ',
   'isYahooFinance': True},
  {'exchange': 'CME',
   'shortname': 'E-Mini S&P 500 Sep 26',
   'quoteType': 'FUTURE',
   'symbol': 'ES=F',
   'index': 'quotes',
   'score': 30538.0,
   'typeDisp': 'Futures',
   'exchDisp': 'Chicago Mercantile Exchange',
   'isYahooFinance': True},
  {'exchange': 'CME',
   'shortname': 'MICRO E-MINI S&P 500 INDEX FUTU',
   'quoteType': 'FUTURE',
   'symbol': 'MES=F',
   'index': 'quotes',
   'score': 30005.0,
   'typeDisp': 'Futures',
   'exchDisp': 'Chicago Mercantile Exchange',
   'isYahooFinance': True},
  {'exchange': 'CME',
   'shortname': 'S&P 500 Annual Dividend Index F',
   'quoteType': 'FUTURE',
   'symbol': 'SDA=F',
   'index': 'quotes',
   'score': 30003.0,
   'typeDisp': 'Futures',
   'exchDisp': 'Chicago Mercantile Exchange',
   'isYahooFinance': True},
  {'exchange': 'CME',
   'shortname': 'TACO on E-mini S&P 500 Futures,',
   'quoteType': 'FUTURE',
   'symbol': 'ESQ=F',
   'index': 'quotes',
   'score': 30001.0,
   'typeDisp': 'Futures',
   'exchDisp': 'Chicago Mercantile Exchange',
   'isYahooFinance': True},
  {'exchange': 'CME',
   'shortname': 'BTIC on E-mini S&P 500 ESG Inde',
   'quoteType': 'FUTURE',
   'symbol': 'EGT=F',
   'index': 'quotes',
   'score': 30001.0,
   'typeDisp': 'Futures',
   'exchDisp': 'Chicago Mercantile Exchange',
   'isYahooFinance': True},
  {'exchange': 'CME',
   'shortname': 'S&P 500 Quarterly Dividend Inde',
   'quoteType': 'FUTURE',
   'symbol': 'SDI=F',
   'index': 'quotes',
   'score': 30001.0,
   'typeDisp': 'Futures',
   'exchDisp': 'Chicago Mercantile Exchange',
   'isYahooFinance': True}],
 'news': [{'uuid': '723a132d-d1e2-3d45-a636-f12bbedde04f',
   'title': 'ProShares Launches Suite of Autocallable Income ETFs',
   'publisher': 'Business Wire',
   'link': 'https://finance.yahoo.com/markets/options/articles/proshares-launches-suite-autocallable-income-123000559.html',
   'providerPublishTime': 1786710600,
   'type': 'STORY',
   'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/U4IM08lZ6AvO7V.YP6Co5w--~B/aD04MDA7dz00MDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/business-wire.com/9859c74b8f742cf85036f166be42b254.jpg',
      'width': 4000,
      'height': 800,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/PIJDFOHyZ3.3v64YoclfnQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/business-wire.com/9859c74b8f742cf85036f166be42b254.jpg',
      'width': 140,
      'height': 140,
      'tag': '140x140'}]},
   'relatedTickers': ['ACQQ', 'ACSP', 'ACRT', '^GSPC', '^RUT']},
  {'uuid': 'e0f96215-91f8-461c-97b9-02f132a5b965',
   'title': 'Stock market today: Dow closes above 52,000 for first time, S&P 500 and Nasdaq rally as tech gains',
   'publisher': 'Yahoo Finance',
   'link': 'https://finance.yahoo.com/markets/stocks/live/stock-market-today-monday-june-29-224230573.html',
   'providerPublishTime': 1782686550,
   'type': 'STORY',
   'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/gfXa8W65t.tHiDRgDaTfww--~B/aD01MjA5O3c9NzgxNDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/a976999b-4852-4a8f-9aab-dbb602f225e7',
      'width': 7814,
      'height': 5209,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/HRKIbop3RPnTwjQnpX.Xsg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://d29szjachogqwa.cloudfront.net/images/2026-04/a976999b-4852-4a8f-9aab-dbb602f225e7',
      'width': 140,
      'height': 140,
      'tag': '140x140'}]},
   'relatedTickers': ['^IXIC',
    '^DJI',
    'GOOGL',
    'GOOG',
    'BZ=F',
    'NVDA',
    'ES=F',
    'YM=F',
    'NQ=F',
    '^GSPC']},
  {'uuid': '8fffa260-4b5a-461c-8c11-cc710a3fe76d',
   'title': 'Stock market today: S&P 500, Nasdaq snap 2-week win streak as AI jitters pressure tech',
   'publisher': 'Yahoo Finance',
   'link': 'https://finance.yahoo.com/markets/live/stock-market-today-sp-500-nasdaq-snap-2-week-win-streak-as-ai-jitters-pressure-tech-231347821.html',
   'providerPublishTime': 1782429227,
   'type': 'STORY',
   'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/MQK322mDgf_IW63R_xyuSA--~B/aD0zMzkxO3c9NTA4NjthcHBpZD15dGFjaHlvbg--/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2025-06/0f4360b0-44a2-11f0-b23a-700d03706262',
      'width': 5086,
      'height': 3391,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/z2KHquQ5wbBGoBRIBnqRaw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2025-06/0f4360b0-44a2-11f0-b23a-700d03706262',
      'width': 140,
      'height': 140,
      'tag': '140x140'}]},
   'relatedTickers': ['YM=F',
    'ES=F',
    'NQ=F',
    '^DJI',
    '^GSPC',
    'OPAI.PVT',
    'AAPL',
    'MU',
    '^IXIC']},
  {'uuid': '5b1aebe4-a7bf-4ae8-a8a4-e6ef64e2f690',
   'title': 'Stocks market today: Dow, S&P 500, Nasdaq rally amid Iran deal optimism as AI chip trade reignites',
   'publisher': 'Yahoo Finance',
   'link': 'https://finance.yahoo.com/markets/live/stocks-market-today-dow-sp-500-nasdaq-rally-amid-iran-deal-optimism-as-ai-chip-trade-reignites-230530576.html',
   'providerPublishTime': 1781737530,
   'type': 'STORY',
   'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/RNxhkAJAONrr3mHY7Z.Bfw--~B/aD0zNTUwO3c9NTMyNTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-06/12757204-7685-4068-afb1-c39610b9f616',
      'width': 5325,
      'height': 3550,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/tb4Ty7gPU6fm6_yzV2XELA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://d29szjachogqwa.cloudfront.net/images/2026-06/12757204-7685-4068-afb1-c39610b9f616',
      'width': 140,
      'height': 140,
      'tag': '140x140'}]},
   'relatedTickers': ['^GSPC',
    '^DJI',
    '^IXIC',
    'QM=F',
    'ES=F',
    'YM=F',
    'NQ=F',
    'CL=F']},
  {'uuid': '6401bdc7-2c0f-42ae-98c4-d3f1cba8739f',
   'title': 'Stock market today: Dow, S&P 500, Nasdaq drop amid rising bond yields',
   'publisher': 'Yahoo Finance',
   'link': 'https://finance.yahoo.com/markets/live/stock-market-today-dow-sp-500-nasdaq-drop-amid-rising-bond-yields-222343798.html',
   'providerPublishTime': 1779143023,
   'type': 'STORY',
   'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/rsXjfAbfovrPBS8DuVJlWw--~B/aD00MDYzO3c9NjA5NTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-05/6fdc999a-d546-4e7a-ac6f-8d194cf02f3d',
      'width': 6095,
      'height': 4063,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/Umf0VmRJEsLdrRbGTTdC0g--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://d29szjachogqwa.cloudfront.net/images/2026-05/6fdc999a-d546-4e7a-ac6f-8d194cf02f3d',
      'width': 140,
      'height': 140,
      'tag': '140x140'}]},
   'relatedTickers': ['NVDA',
    'NQ=F',
    'YM=F',
    'ES=F',
    '^DJI',
    'CL=F',
    '^IXIC',
    '^GSPC']}],
 'nav': [],
 'lists': [],
 'researchReports': [],
 'screenerFieldResults': [],
 'totalTime': 40,
 'timeTakenForQuotes': 423,
 'timeTakenForNews': 600,
 'timeTakenForAlgowatchlist': 400,
 'timeTakenForPredefinedScreener': 400,
 'timeTakenForCrunchbase': 0,
 'timeTakenForNav': 400,
 'timeTakenForResearchReports': 0,
 'timeTakenForQuestions': 0,
 'timeTakenForScreenerField': 0,
 'timeTakenForCulturalAssets': 0,
 'timeTakenForSearchLists': 0}

In [22]:
op_search_results=[]
count=0
for i in search_results["quotes"]:
    if i["quoteType"]=="EQUITY" and count<5:
        op_search_results.append(i)
        count+=1

In [23]:
op_search_results[0]

{'exchange': 'NGM',
 'quoteType': 'EQUITY',
 'symbol': 'ACSP',
 'index': 'quotes',
 'score': 100001.0,
 'typeDisp': 'Equity',
 'longname': 'ProShares S&P 500 Autocallable Income ETF',
 'exchDisp': 'NASDAQ',
 'isYahooFinance': True}

CODE FOR PRINTING LIST OF TOP 5 COMPANIES AFTER SEARCH AND TAKING INPUT

In [24]:
serial=0
for i in op_search_results:
    serial=serial+1
    print(serial,". ",i["shortname"],"(",i["symbol"],")")
choice=1
print("chosen company=",op_search_results[choice-1]["shortname"],"(",op_search_results[choice-1]["symbol"],")")

KeyError: 'shortname'

In [18]:

data=yf.Ticker("MSFT")

In [19]:
df=data.history(period="1y")

In [15]:
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-15 00:00:00-04:00,233.138774,233.417742,228.495921,230.737640,56038700,0.0,0.0
2025-08-18 00:00:00-04:00,230.847254,232.262026,229.263109,230.040237,37476200,0.0,0.0
2025-08-19 00:00:00-04:00,230.428792,232.012937,228.505903,229.711441,39402600,0.0,0.0
2025-08-20 00:00:00-04:00,229.133567,229.621769,224.939070,225.178177,42263900,0.0,0.0
2025-08-21 00:00:00-04:00,225.437234,225.686314,222.956393,224.072266,30621200,0.0,0.0

In [25]:
df.head(10)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-08-15 00:00:00-04:00,518.627468,521.931037,514.966706,516.048035,25213300,0.00,0.0
2025-08-18 00:00:00-04:00,517.456790,518.677024,509.946770,513.002319,23760600,0.00,0.0
2025-08-19 00:00:00-04:00,510.919005,511.077711,504.520105,505.730438,21481000,0.00,0.0
2025-08-20 00:00:00-04:00,505.829633,506.950683,500.442669,501.712524,27723000,0.00,0.0
2025-08-21 00:00:00-04:00,500.520093,504.435300,499.556197,501.066620,18443300,0.83,0.0
2025-08-22 00:00:00-04:00,501.076555,507.515784,499.248138,504.037811,24324200,0.00,0.0
2025-08-25 00:00:00-04:00,503.441597,504.991777,500.947384,501.086517,21638600,0.00,0.0
2025-08-26 00:00:00-04:00,501.185870,501.801993,495.372710,498.880493,30835700,0.00,0.0
2025-08-27 00:00:00-04:00,498.840743,504.097460,496.753953,503.550903,17277900,0.00,0.0
2025-08-28 00:00:00-04:00,503.898678,507.873504,502.318688,506.432648,18015600,0.00,0.0

In [28]:
df.duplicated()

Date
2025-08-15 00:00:00-04:00    False
2025-08-18 00:00:00-04:00    False
2025-08-19 00:00:00-04:00    False
2025-08-20 00:00:00-04:00    False
2025-08-21 00:00:00-04:00    False
                             ...
2026-08-10 00:00:00-04:00    False
2026-08-11 00:00:00-04:00    False
2026-08-12 00:00:00-04:00    False
2026-08-13 00:00:00-04:00    False
2026-08-14 00:00:00-04:00    False
Length: 251, dtype: bool